### ISSUE TITLE
Ensure correcty tying of API key's restrictSources parameter

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-java#680] opened 2020-03-13 12:19 UTC
The `restrictSources` of API keys should be typed as:

 - a comma-separated string

This parameter does **not** support array of strings as a valid type.

**Comment by Ant-hem** [comment] 2020-03-16 07:55
Duplicate of #676 ?

**Comment by aseure** [comment] 2020-03-26 13:40
Yes indeed! Closing in favor of #676

**Closed as completed** 2020-06-09 12:03 UTC
Labels: Bug, Good First Issue
